name: BuildDeploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Catalog
      run: dotnet restore
    - name: Build
      working-directory: ./Catalog
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Catalog
      run: dotnet test --no-build --verbosity normal
      
  deploy:
  
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 9c290e67-f188-47fd-bcd3-df00d584f702
          heroku_app_name: configuracion-final
          heroku_email: carlosroque198@gmail.com
        
